baseURL = 'https://ediardo.com/'
languageCode = 'en-us'
title = 'Eddie Ramirez'
theme = 'PaperMod'

[markup.goldmark.renderer]
    unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'